# Import NumPy so we can create the prescribed sediment-flux array.
import numpy as np

# Import pytest for numerical comparisons and test utilities.
import pytest

# Import the RasterModelGrid used to construct the synthetic landscape.
from landlab import RasterModelGrid

# Import the existing FlowAccumulator because our new component
# intentionally reuses Landlab's existing MFD routing network.
from landlab.components import FlowAccumulator

# Import the MFD sediment-routing component that we are developing.
from landlab.components.flow_accum.flow_accumulator_mfd_marine_deposition import (
    FlowAccumulatorMFDSediment,
)


def test_mfd_sediment_routing_from_single_source():
    # Create a 10 x 10 raster grid.
    # This is the same grid size used by Landlab's existing MFD tests.
    mg = RasterModelGrid((10, 10))

    # Create a planar surface with equal slopes in x and y.
    # This produces a simple MFD branching pattern.
    mg.add_field(
        "topographic__elevation",
        mg.node_y + mg.node_x,
        at="node",
    )

    # Create Landlab's existing MFD flow-routing component.
    # Our sediment component will reuse the routing information produced here.
    fa = FlowAccumulator(
        mg,
        flow_director="FlowDirectorMFD",
    )

    # Calculate the MFD routing network.
    fa.run_one_step()

    # Select the first core node.
    # Core nodes are interior nodes where the planar slope produces
    # two downstream MFD receivers in this test geometry.
    source_node = mg.core_nodes[0]

    # Create a sediment-flux array with zero sediment everywhere.
    # This isolates the transport from one known source node.
    sediment_flux = np.zeros(mg.number_of_nodes)

    # Put 100 units of sediment flux at the selected source node.
    sediment_flux[source_node] = 100.0

    # Create our MFD sediment-routing component using the existing
    # MFD receiver network.
    sediment = FlowAccumulatorMFDSediment(
        mg,
        sediment_flux,
    )

    # Run the sediment-routing calculation.
    sediment.run_one_step()

    # Get the receiver IDs generated by Landlab's MFD router.
    receivers = mg.at_node["flow__receiver_node"]

    # Get the corresponding MFD routing proportions.
    proportions = mg.at_node["flow__receiver_proportions"]

    # Identify the active receiver entries for our source node.
    # Invalid receiver slots have zero proportion or a self-reference.
    active = (proportions[source_node] > 0.0) & (
        receivers[source_node] != source_node
    )

    # Calculate the total sediment flux that was routed out of
    # the source node.
    routed_flux = 0.0

    # Examine each active downstream receiver of the source node.
    for receiver, proportion in zip(
        receivers[source_node, active],
        proportions[source_node, active],
    ):
        # Calculate the sediment flux sent along this MFD branch.
        branch_flux = proportion * sediment_flux[source_node]

        # Add this branch to the total routed sediment flux.
        routed_flux += branch_flux

        # Check that the downstream node received the expected
        # contribution from the source node.
        assert sediment._sediment_influx[receiver] == pytest.approx(
            branch_flux
        )

    # Verify that all sediment leaving the source node was distributed
    # among the MFD receivers.
    assert routed_flux == pytest.approx(
        sediment_flux[source_node]
    )

# def test_mfd_sediment_routing_from_two_sources():
#     # Create a simple 10 x 10 raster grid.
#     mg = RasterModelGrid((10, 10))

#     # Create a planar surface with equal slopes in x and y.
#     # This gives the MFD router a predictable branching pattern.
#     mg.add_field(
#         "topographic__elevation",
#         mg.node_y + mg.node_x,
#         at="node",
#     )

#     # Create Landlab's existing MFD flow-routing component.
#     fa = FlowAccumulator(
#         mg,
#         flow_director="FlowDirectorMFD",
#     )

#     # Calculate the MFD routing network.
#     fa.run_one_step()

#     # Get the receiver-node array produced by the MFD router.
#     receivers = mg.at_node["flow__receiver_node"]

#     # Get the corresponding routing proportions.
#     proportions = mg.at_node["flow__receiver_proportions"]

#     # Find core nodes that have more than one active downstream receiver.
#     branching_nodes = np.sum(proportions > 0.0, axis=1) > 1

#     # Select two branching nodes from the MFD network.
#     source_nodes = mg.core_nodes[branching_nodes[mg.core_nodes]][:2]

#     # Make sure the test actually found two suitable source nodes.
#     assert len(source_nodes) == 2

#     # Create a sediment-flux array with no sediment supplied elsewhere.
#     sediment_flux = np.zeros(mg.number_of_nodes)

#     # Give the first source node 100 units of sediment flux.
#     sediment_flux[source_nodes[0]] = 100.0

#     # Give the second source node 50 units of sediment flux.
#     sediment_flux[source_nodes[1]] = 50.0

#     # Create our MFD sediment-routing component.
#     sediment = FlowAccumulatorMFDSediment(
#         mg,
#         sediment_flux,
#     )

#     # Route the sediment through the existing MFD network.
#     sediment.run_one_step()

#     # Independently calculate the sediment contribution expected
#     # at every downstream node.
#     expected_influx = sediment_flux.copy()

#     # Process each source node independently.
#     for source_node in source_nodes:

#         # Find the active downstream receiver slots for this source.
#         active = (proportions[source_node] > 0.0) & (
#             receivers[source_node] != source_node
#         )

#         # Distribute this source's sediment among its MFD receivers.
#         for receiver, proportion in zip(
#             receivers[source_node, active],
#             proportions[source_node, active],
#         ):
#             # Add this source's contribution to the downstream receiver.
#             expected_influx[receiver] += (
#                 proportion * sediment_flux[source_node]
#             )

#     # Check that the component's calculated influx agrees with
#     # the independently calculated expected influx.
#     assert np.allclose(
#         sediment._sediment_influx,
#         expected_influx,
#     )

# Test that sediment from two different upstream nodes is accumulated
# at the same downstream receiver.
def test_mfd_sediment_routing_from_two_converging_sources():

    # Create the same simple raster grid used by the first MFD sediment test.
    mg = RasterModelGrid((10, 10))

    # Create a planar topography with equal slopes in x and y.
    # This produces a predictable MFD network with branching flow.
    mg.add_field(
        "topographic__elevation",
        mg.node_y + mg.node_x,
        at="node",
    )

    # Create Landlab's existing MFD flow-routing component.
    # We reuse its routing topology rather than implementing MFD routing again.
    fa = FlowAccumulator(
        mg,
        flow_director="FlowDirectorMFD",
    )

    # Calculate the MFD receiver and proportion fields.
    fa.run_one_step()

    # Get the receiver-node array produced by Landlab's MFD router.
    receivers = mg.at_node["flow__receiver_node"]

    # Get the routing proportion associated with every receiver.
    proportions = mg.at_node["flow__receiver_proportions"]

    # Create a dictionary that will store all upstream nodes
    # that send flow directly to each receiver.
    upstream_by_receiver = {}

    # Examine every node in the grid.
    for node in range(mg.number_of_nodes):

        # Identify the active receiver slots for this node.
        active = (proportions[node] > 0.0) & (
            receivers[node] != node
        )

        # Examine every active downstream receiver of this node.
        for receiver in receivers[node, active]:

            # Create an empty list for this receiver if it does not
            # already exist in the dictionary.
            upstream_by_receiver.setdefault(
                receiver,
                [],
            )

            # Record this node as an upstream contributor to the receiver.
            upstream_by_receiver[receiver].append(node)

    # Find a receiver that has at least two direct upstream contributors.
    converging_receiver = None

    # Examine each receiver and its list of upstream contributors.
    for receiver, upstream_nodes in upstream_by_receiver.items():

        # We need at least two different upstream nodes for a convergence test.
        if len(upstream_nodes) >= 2:

            # Save the first receiver that satisfies this condition.
            converging_receiver = receiver

            # Stop searching once a suitable convergence has been found.
            break

    # Make sure the MFD network actually contains a convergence point.
    assert converging_receiver is not None

    # Retrieve the upstream nodes that directly contribute to the
    # selected convergence point.
    source_nodes = upstream_by_receiver[converging_receiver][:2]

    # Create a sediment-flux array with zero sediment everywhere.
    sediment_flux = np.zeros(mg.number_of_nodes)

    # Give the first upstream source 100 units of sediment flux.
    sediment_flux[source_nodes[0]] = 100.0

    # Give the second upstream source 50 units of sediment flux.
    sediment_flux[source_nodes[1]] = 50.0

    # Create our MFD sediment-routing component.
    sediment = FlowAccumulatorMFDSediment(
        mg,
        sediment_flux,
    )

    # Route the sediment through the complete MFD network.
    sediment.run_one_step()

    # Calculate the sediment contribution from the first source
    # to the selected convergence point.
    first_contribution = (
        proportions[source_nodes[0]]
        [receivers[source_nodes[0]] == converging_receiver][0]
        * sediment_flux[source_nodes[0]]
    )

    # Calculate the sediment contribution from the second source
    # to the same convergence point.
    second_contribution = (
        proportions[source_nodes[1]]
        [receivers[source_nodes[1]] == converging_receiver][0]
        * sediment_flux[source_nodes[1]]
    )

    # Add the two independent upstream contributions.
    expected_influx = first_contribution + second_contribution

    # Check that our component added both contributions at the
    # common downstream receiver rather than overwriting one.
    assert sediment._sediment_influx[converging_receiver] == pytest.approx(
        expected_influx
    )


# Test global sediment conservation from a source through the
# complete MFD routing network to the outlet boundary.
def test_mfd_sediment_global_conservation():

    # Create a simple 10 x 10 raster grid.
    # We use the same geometry as our previous MFD routing tests
    # so that the routing behavior is familiar.
    mg = RasterModelGrid((10, 10))

    # Create a planar topographic surface with equal slopes in x and y.
    # This produces a predictable MFD drainage network.
    mg.add_field(
        "topographic__elevation",
        mg.node_y + mg.node_x,
        at="node",
    )

    # Create Landlab's existing MFD flow-routing component.
    # We are testing sediment conservation on top of an already
    # established MFD routing network.
    fa = FlowAccumulator(
        mg,
        flow_director="FlowDirectorMFD",
    )

    # Calculate the MFD receivers, proportions, and upstream ordering.
    # These fields define the network through which sediment will move.
    fa.run_one_step()

    # Get the downstream receiver of every node.
    # Each row contains the possible downstream MFD receivers.
    receivers = mg.at_node["flow__receiver_node"]

    # Get the MFD proportion associated with each receiver.
    # The active proportions for a node should sum to one.
    proportions = mg.at_node["flow__receiver_proportions"]

    # # Identify nodes that have at least one active downstream receiver.
    # # A positive proportion means that the node sends sediment
    # # to that receiver.
    # has_receiver = np.any(
    #     proportions > 0.0,
    #     axis=1,
    # )

    # # Identify outlet nodes as nodes with no active downstream receiver.
    # # These nodes represent the boundary through which sediment
    # # leaves the routing network.
    # outlet_nodes = ~has_receiver

    # # Make sure that the test geometry actually contains at least
    # # one outlet node.
    # assert np.any(outlet_nodes)

    # Identify nodes that have a real downstream receiver.
    # A receiver is real only when its proportion is positive and
    # the receiver is different from the node itself.
    has_downstream_receiver = np.any(
        (proportions > 0.0)
        & (receivers != np.arange(mg.number_of_nodes)[:, None]),
        axis=1,
    )

    # Nodes without a real downstream receiver are the outlet nodes.
    # In this Landlab MFD configuration, these correspond to boundary nodes.
    outlet_nodes = ~has_downstream_receiver

    # Verify that the routing network contains outlet nodes.
    assert np.any(outlet_nodes)

    # Verify the specific Landlab boundary convention that we observed.
    # The outlet nodes should be exactly the grid boundary nodes.
    assert np.array_equal(
        np.sort(np.where(outlet_nodes)[0]),
        np.sort(mg.boundary_nodes),
    )


    # Select one interior core node as the sediment source.
    # Using a core node ensures that sediment begins inside the
    # drainage network rather than directly at the boundary.
    source_node = mg.core_nodes[0]

    # Make sure the selected source is not itself an outlet.
    # Otherwise the conservation test would not test routing.
    assert not outlet_nodes[source_node]

    # Create a sediment-flux array containing no sediment initially.
    # This lets us prescribe sediment at exactly one source.
    sediment_flux = np.zeros(
        mg.number_of_nodes,
    )

    # Introduce 100 units of sediment flux at the source node.
    # This is the total amount of sediment entering our system.
    sediment_flux[source_node] = 100.0

    # Calculate the total sediment entering the routing system.
    # Only the prescribed source contributes sediment in this test.
    total_input = np.sum(
        sediment_flux,
    )

    # Create the MFD sediment-routing component.
    # The component will transport the prescribed sediment through
    # the complete MFD network.
    sediment = FlowAccumulatorMFDSediment(
        mg,
        sediment_flux,
    )

    # Run the complete MFD sediment-routing calculation.
    # Sediment will be propagated through the downstream network.
    sediment.run_one_step()

    # Extract the sediment flux at all outlet nodes.
    # These are the locations where sediment leaves the routing system.
    outlet_flux = sediment._sediment_outflux[outlet_nodes]

    # Add the sediment flux from all outlets.
    # This gives the total amount of sediment leaving the system.
    total_output = np.sum(
        outlet_flux,
    )

    # Compare the total sediment entering the system with the
    # total sediment leaving the system.
    # For a routing-only calculation, these quantities must agree.
    assert total_output == pytest.approx(
        total_input,
    )


# Test that sediment is conserved locally at every node in the MFD network.
def test_mfd_sediment_node_by_node_conservation():

    # Create the same 10 x 10 raster grid used by the previous tests.
    # Using the same geometry makes the MFD network familiar and reproducible.
    mg = RasterModelGrid((10, 10))

    # Create a planar topographic surface with equal slopes in x and y.
    # This produces a predictable multiple-flow-direction network.
    mg.add_field(
        "topographic__elevation",
        mg.node_y + mg.node_x,
        at="node",
    )

    # Create Landlab's existing MFD flow-routing component.
    # We reuse its receiver and proportion fields instead of implementing
    # the MFD water-routing algorithm ourselves.
    fa = FlowAccumulator(
        mg,
        flow_director="FlowDirectorMFD",
    )

    # Calculate the MFD routing network.
    # This populates the receiver, proportion, and upstream-order fields.
    fa.run_one_step()

    # Get the receiver-node array produced by Landlab.
    # Each row contains the possible downstream receivers for one node.
    receivers = mg.at_node["flow__receiver_node"]

    # Get the MFD routing proportions.
    # Each proportion specifies what fraction of sediment is sent
    # to the corresponding receiver.
    proportions = mg.at_node["flow__receiver_proportions"]

    # Create a sediment-flux array with a different positive flux
    # at every node.
    # Using different values makes it easier to detect accidental
    # mixing or overwriting of sediment fluxes.
    sediment_flux = np.arange(
        1.0,
        mg.number_of_nodes + 1.0,
    )

    # Create the MFD sediment-routing component.
    # The component will use the existing MFD routing network.
    sediment = FlowAccumulatorMFDSediment(
        mg,
        sediment_flux,
    )

    # Run the complete sediment-routing calculation.
    # This calculates the sediment flux available at every node
    # after upstream sediment has been accumulated.
    sediment.run_one_step()

    # Examine every node in the grid.
    # We will test the MFD conservation equation independently at each node.
    for node in range(mg.number_of_nodes):

        # Identify the receiver slots that represent real downstream
        # routing paths from this node.
        # Positive proportion means the receiver is active.
        # A self-receiver represents a boundary node and is excluded.
        active = (proportions[node] > 0.0) & (
            receivers[node] != node
        )

        # Store the total sediment flux distributed from this node.
        # We will add the contribution sent to each active receiver.
        routed_flux = 0.0

        # Examine every active receiver of this node together with
        # its corresponding MFD routing proportion.
        for receiver, proportion in zip(
            receivers[node, active],
            proportions[node, active],
        ):
            # Calculate the sediment flux sent from this node
            # to this particular downstream receiver.
            branch_flux = (
                proportion * sediment._sediment_outflux[node]
            )

            # Add this branch contribution to the total sediment
            # leaving this node.
            routed_flux += branch_flux

        # Verify the local conservation equation:
        #
        # sum(p_ij * Q_s,i) = Q_s,i
        #
        # The total sediment distributed among all active receivers
        # must equal the sediment flux available at this node.
        if np.any(active):
            assert routed_flux == pytest.approx(
                sediment._sediment_outflux[node]
            )